Add Requirement template
tiiuae/UTM-Security-Verifier pull request #3
Opened 2024-05-17 05:50 UTC by govindsi

2024-06-14 12:52 UTC, hrishiballal requested changes

2024-06-19 13:38 UTC, govindsi commented on requirements/usv_req.md
> +| Regulatory Requirement                      | Standard        | Asset                                                                                      | State of the Art           | Verifier Re
done

2024-06-19 13:39 UTC, govindsi commented on requirements/usv_req.md
> +| Regulatory Requirement                      | Standard        | Asset                                                                                      | State of the Art           | Verifier Re
done

2024-06-19 13:39 UTC, govindsi commented on requirements/usv_req.md
> +| Regulatory Requirement                      | Standard        | Asset                                                                                      | State of the Art           | Verifier Re
done

2024-06-19 13:40 UTC, govindsi commented on requirements/usv_req.md
> +| Article 8 - Network Identification          | ASTM F3411-22a  | Network Identification Data                                                                | TLS 1.3, Oauth2.0, Signing | VRID-002
i was referring to state of art mitigation, i have mapped with CIA. I am thinning details we will outline separately.

2024-06-19 13:40 UTC, govindsi commented on requirements/usv_req.md
> +| Article 10 - UAS Flight Authorization       | ASTM F3548-21   | Flight Authorization Data                                                                  | TLS 1.3, Oauth2.0, Signing | VRID-004
done

2024-06-19 13:40 UTC, govindsi commented on requirements/usv_req.md
> +| Article 11 - Traffic Information            | NA              | Traffic Information Data                                                                   | TLS 1.3, Oauth2.0, Signing | VRID-005
i was referring to state of art mitigation, i have mapped with CIA. I am thinning details we will outline separately.

2024-06-19 13:41 UTC, govindsi commented on requirements/usv_req.md
> +| Article 13 - Conformance Monitoring         | ASTM F3548-21   | Conformance Monitoring Data                                                                | TLS 1.3, Oauth2.0, Signing | VRID-006
i have mapped to NA

2024-06-20 17:07 UTC, hrishiballal approved these changes

2024-06-20 17:07 UTC, merged